# Generated by Django 3.1.6 on 2021-04-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcr_system', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcrhigher',
            name='supervised_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_higher_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcrhigher',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_higher_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_client_name', to='user.clienttable'),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_client_type', to='user.clienttype'),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='mpo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_mpo_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_product', to='dcr_system.productinformation'),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_sample_product', to='dcr_system.productinformation'),
        ),
        migrations.AddField(
            model_name='dailycallreport',
            name='visited_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_visited_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
