# Generated by Django 3.1.6 on 2021-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('TA', models.FloatField()),
                ('DA', models.FloatField()),
                ('others', models.FloatField()),
                ('remarks', models.CharField(max_length=250)),
                ('miscellaneous', models.FloatField()),
                ('visited_area', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status1', models.CharField(max_length=250)),
                ('status2', models.CharField(max_length=250)),
            ],
        ),
    ]
