# Generated by Django 3.1.6 on 2021-04-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryexpense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_expense_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryexpense',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_expense_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
