# Generated by Django 3.1.6 on 2021-04-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_plan_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplanhigher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_higher_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplanhigher',
            name='evening_supervised',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplanhigher',
            name='morning_supervised',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplanhigher',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_higher_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='approver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_plan_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
