# Generated by Django 3.1.6 on 2021-04-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='report_initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavereport',
            name='report_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavereport',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminreport',
            name='report_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminreport',
            name='report_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_writer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminreport',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
