# Generated by Django 3.2 on 2021-04-23 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcr_system', '0003_auto_20210423_0726'),
        ('user', '0006_usercontroltable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_generator', '0003_dailycallreport_dcrhigher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('qunatity', models.IntegerField()),
                ('updated_date', models.DateField(auto_now=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cleint_name', to='user.clienttable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_product', to='dcr_system.productinformation')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_sale_person', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
