# Generated by Django 3.1.6 on 2021-04-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation_name',
        ),
    ]
