# Generated by Django 3.1.6 on 2021-04-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_designation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.designation'),
            preserve_default=False,
        ),
    ]
