# Generated by Django 3.1.6 on 2021-04-22 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserControlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervised', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uct_supervised', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uct_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
